In [23]:
#1. What is a Python library? Why do we use Python libraries?

#Collection of functions called as Python Library. Python functions are reusable and optimized version in Python libraries. 


In [24]:
#2. What is the difference between Numpy array and List?

#NumPy arrays have a fixed data type, enabling efficient numerical operations and reduced memory usage, while Python lists can store elements of varying data types and are more general-purpose but may be less efficient for numerical computations. NumPy also provides concise syntax for array operations, whereas lists often require explicit iteration.

In [25]:
#3. Find the shape, size and dimension of the following array?

import numpy as np

arr = np.array([[1, 2, 3, 4],

                [5, 6, 7, 8],

                [9, 10, 11, 12]
               ])

# Shape function
shape = arr.shape

# Size function
size = arr.size

# Dimension function
dimension = arr.ndim

print("Shape:", shape)
print("Size:", size)
print("Dimension:", dimension)

Shape: (3, 4)
Size: 12
Dimension: 2


In [26]:
#4. Write python code to access the first row of the following array?

import numpy as np

arr1 = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12]
                ])

arr1[0]

array([1, 2, 3, 4])

In [27]:
#5. How do you access the element at the third row and fourth column from the given numpy array?


arr1[2][3]



12

In [28]:
#6. Write code to extract all odd-ineexed elements from the given numpy array?

import numpy as np

arr2 = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

arr2[:, 1::2].flatten()



array([ 2,  4,  6,  8, 10, 12])

In [29]:
#7. How can you generate a random 3x3 matrix with values between 0 and 1?

import numpy as np

np.random.rand(3, 3)



array([[0.17641103, 0.42540785, 0.33875835],
       [0.85746248, 0.34127667, 0.6384248 ],
       [0.88672515, 0.1902777 , 0.60172656]])

In [30]:
#8. Describe the difference between np.random.rand and np.random.randn?


#np.random.rand generates random numbers from a uniform distribution between 0 and 1, while np.random.randn generates numbers from a standard normal distribution with mean 0 and standard deviation 1

In [31]:
#9. Write code to increase the dimension of the following array?

import numpy as np

darray = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

# Increase dimension along a new axis (for example, adding a new axis at the end)
darray.reshape(2,2)



ValueError: cannot reshape array of size 12 into shape (2,2)

In [32]:
#10. How to transpose the following array in NumPy?
o_array = np.array([[1, 2, 3, 4],
                    [5, 6, 7, 8],
                    [9, 10, 11, 12]])

o_array.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [33]:
#11. Consider the following matrix:
#Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
#Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

#Perform the following operation using Python1

#1. Index wise multiplication
#2. Matix multiplication
#3. Add both the matrics
#4. Subtract matrix B from A 
#5. Divide Matix B by A


In [34]:
#1. Index wise multiplication

import numpy as np


arrayA2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])
arrayB2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])



In [35]:
arrayA2 * arrayB2

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [36]:
#2. Matix multiplication

arrayA2 @ arrayB2

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 4)

In [37]:
#3. Add both the matrics

arrayA2 + arrayB2

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [38]:
#4. Subtract matrix B from A 

arrayA2 - arrayB2

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [39]:
#5. Divide Matix B by A


arrayB2 /  arrayA2


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [40]:
#12. Which function in Numpy can be used to swap the byte order of an array?

#Ans - In NumPy, you can use the byteswap function to swap the byte order of an array. The byteswap function swaps the byte order of the elements in the array in place.


In [41]:
#13. What is the significance of the np.linalg.inv function?

#Ans - The np.linalg.inv function in NumPy is used to compute the (multiplicative) inverse of a square matrix. In other words, if you have a square matrix A, then np.linalg.inv(A) will give you a matrix B such that the product of A and B is the identity matrix.

In [42]:
#14. What does the np.reshape function do, and how is it used?

#Ans - The np.reshape function in NumPy is used to give a new shape to an array without changing its data. It returns a new array with the specified shape. The new shape should have the same number of elements as the original array.

In [22]:
#15. What is broadcasting in Numpy?

#Ans - The broadcasting rules in NumPy allow arrays with different shapes to be combined in a way that makes sense for arithmetic operations(subtract,addition,multiplication,divide of each elements). The smaller array is "broadcast" across the larger one so that they have compatible shapes.